name: ldtvenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - defaults::python=3.12.7
  - pytorch=2.5.0
  - torchvision=0.20.0
  - pytorch-cuda=11.8
  - pip
  - pip:
      - mss==9.2.0
      - easyocr==1.7.2
      - opencv-contrib-python-headless==4.10.0.84
      - Pillow==11.0.0
      - websockets==13.1
      - transformers==4.46.0
      - pyinstaller==6.11.0
      - sentencepiece==0.2.0
      - sacremoses==0.1.1
      - dl-translate==0.3.1
